// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package com.jackxue.netty.example01;

public final class MessageData {
  private MessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.jackxue.netty.example01.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PersonType = 1;</code>
     */
    PersonType(1),
    /**
     * <code>CatType = 2;</code>
     */
    CatType(2),
    /**
     * <code>DogType = 3;</code>
     */
    DogType(3),
    ;

    /**
     * <code>PersonType = 1;</code>
     */
    public static final int PersonType_VALUE = 1;
    /**
     * <code>CatType = 2;</code>
     */
    public static final int CatType_VALUE = 2;
    /**
     * <code>DogType = 3;</code>
     */
    public static final int DogType_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 1: return PersonType;
        case 2: return CatType;
        case 3: return DogType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jackxue.netty.example01.MessageData.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jackxue.netty.example01.DataType)
  }

  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jackxue.netty.example01.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
     * @return Whether the dataType field is set.
     */
    boolean hasDataType();
    /**
     * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
     * @return The dataType.
     */
    com.jackxue.netty.example01.MessageData.DataType getDataType();

    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     * @return The person.
     */
    com.jackxue.netty.example01.MessageData.Person getPerson();
    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     */
    com.jackxue.netty.example01.MessageData.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     * @return Whether the cat field is set.
     */
    boolean hasCat();
    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     * @return The cat.
     */
    com.jackxue.netty.example01.MessageData.Cat getCat();
    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     */
    com.jackxue.netty.example01.MessageData.CatOrBuilder getCatOrBuilder();

    public com.jackxue.netty.example01.MessageData.MyMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code com.jackxue.netty.example01.MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jackxue.netty.example01.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.jackxue.netty.example01.MessageData.DataType value = com.jackxue.netty.example01.MessageData.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.jackxue.netty.example01.MessageData.Person.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.jackxue.netty.example01.MessageData.Person) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.jackxue.netty.example01.MessageData.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.jackxue.netty.example01.MessageData.Person) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.jackxue.netty.example01.MessageData.Cat.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.jackxue.netty.example01.MessageData.Cat) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.jackxue.netty.example01.MessageData.Cat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.jackxue.netty.example01.MessageData.Cat) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jackxue.netty.example01.MessageData.MyMessage.class, com.jackxue.netty.example01.MessageData.MyMessage.Builder.class);
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PERSON(2),
      CAT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return PERSON;
          case 3: return CAT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
     * @return Whether the dataType field is set.
     */
    @java.lang.Override public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public com.jackxue.netty.example01.MessageData.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.jackxue.netty.example01.MessageData.DataType result = com.jackxue.netty.example01.MessageData.DataType.valueOf(dataType_);
      return result == null ? com.jackxue.netty.example01.MessageData.DataType.PersonType : result;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     * @return The person.
     */
    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.Person getPerson() {
      if (dataBodyCase_ == 2) {
         return (com.jackxue.netty.example01.MessageData.Person) dataBody_;
      }
      return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
    }
    /**
     * <code>.com.jackxue.netty.example01.Person person = 2;</code>
     */
    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.PersonOrBuilder getPersonOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.jackxue.netty.example01.MessageData.Person) dataBody_;
      }
      return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
    }

    public static final int CAT_FIELD_NUMBER = 3;
    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     * @return Whether the cat field is set.
     */
    @java.lang.Override
    public boolean hasCat() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     * @return The cat.
     */
    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.Cat getCat() {
      if (dataBodyCase_ == 3) {
         return (com.jackxue.netty.example01.MessageData.Cat) dataBody_;
      }
      return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
    }
    /**
     * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
     */
    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.CatOrBuilder getCatOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.jackxue.netty.example01.MessageData.Cat) dataBody_;
      }
      return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.jackxue.netty.example01.MessageData.Person) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.jackxue.netty.example01.MessageData.Cat) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.jackxue.netty.example01.MessageData.Person) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.jackxue.netty.example01.MessageData.Cat) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jackxue.netty.example01.MessageData.MyMessage)) {
        return super.equals(obj);
      }
      com.jackxue.netty.example01.MessageData.MyMessage other = (com.jackxue.netty.example01.MessageData.MyMessage) obj;

      if (hasDataType() != other.hasDataType()) return false;
      if (hasDataType()) {
        if (dataType_ != other.dataType_) return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 3:
          if (!getCat()
              .equals(other.getCat())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CAT_FIELD_NUMBER;
          hash = (53 * hash) + getCat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jackxue.netty.example01.MessageData.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jackxue.netty.example01.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jackxue.netty.example01.MyMessage)
        com.jackxue.netty.example01.MessageData.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jackxue.netty.example01.MessageData.MyMessage.class, com.jackxue.netty.example01.MessageData.MyMessage.Builder.class);
      }

      // Construct using com.jackxue.netty.example01.MessageData.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.MyMessage getDefaultInstanceForType() {
        return com.jackxue.netty.example01.MessageData.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.MyMessage build() {
        com.jackxue.netty.example01.MessageData.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.MyMessage buildPartial() {
        com.jackxue.netty.example01.MessageData.MyMessage result = new com.jackxue.netty.example01.MessageData.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (personBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = personBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (catBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = catBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jackxue.netty.example01.MessageData.MyMessage) {
          return mergeFrom((com.jackxue.netty.example01.MessageData.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jackxue.netty.example01.MessageData.MyMessage other) {
        if (other == com.jackxue.netty.example01.MessageData.MyMessage.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getDataBodyCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case CAT: {
            mergeCat(other.getCat());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jackxue.netty.example01.MessageData.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jackxue.netty.example01.MessageData.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
       * @return Whether the dataType field is set.
       */
      @java.lang.Override public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.jackxue.netty.example01.MessageData.DataType result = com.jackxue.netty.example01.MessageData.DataType.valueOf(dataType_);
        return result == null ? com.jackxue.netty.example01.MessageData.DataType.PersonType : result;
      }
      /**
       * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.jackxue.netty.example01.MessageData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.jackxue.netty.example01.DataType dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.jackxue.netty.example01.MessageData.Person, com.jackxue.netty.example01.MessageData.Person.Builder, com.jackxue.netty.example01.MessageData.PersonOrBuilder> personBuilder_;
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       * @return Whether the person field is set.
       */
      @java.lang.Override
      public boolean hasPerson() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       * @return The person.
       */
      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Person getPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.jackxue.netty.example01.MessageData.Person) dataBody_;
          }
          return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return personBuilder_.getMessage();
          }
          return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      public Builder setPerson(com.jackxue.netty.example01.MessageData.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      public Builder setPerson(
          com.jackxue.netty.example01.MessageData.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      public Builder mergePerson(com.jackxue.netty.example01.MessageData.Person value) {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.jackxue.netty.example01.MessageData.Person.getDefaultInstance()) {
            dataBody_ = com.jackxue.netty.example01.MessageData.Person.newBuilder((com.jackxue.netty.example01.MessageData.Person) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      public com.jackxue.netty.example01.MessageData.Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.PersonOrBuilder getPersonOrBuilder() {
        if ((dataBodyCase_ == 2) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.jackxue.netty.example01.MessageData.Person) dataBody_;
          }
          return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.com.jackxue.netty.example01.Person person = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jackxue.netty.example01.MessageData.Person, com.jackxue.netty.example01.MessageData.Person.Builder, com.jackxue.netty.example01.MessageData.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jackxue.netty.example01.MessageData.Person, com.jackxue.netty.example01.MessageData.Person.Builder, com.jackxue.netty.example01.MessageData.PersonOrBuilder>(
                  (com.jackxue.netty.example01.MessageData.Person) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.jackxue.netty.example01.MessageData.Cat, com.jackxue.netty.example01.MessageData.Cat.Builder, com.jackxue.netty.example01.MessageData.CatOrBuilder> catBuilder_;
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       * @return Whether the cat field is set.
       */
      @java.lang.Override
      public boolean hasCat() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       * @return The cat.
       */
      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Cat getCat() {
        if (catBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.jackxue.netty.example01.MessageData.Cat) dataBody_;
          }
          return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return catBuilder_.getMessage();
          }
          return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      public Builder setCat(com.jackxue.netty.example01.MessageData.Cat value) {
        if (catBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          catBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      public Builder setCat(
          com.jackxue.netty.example01.MessageData.Cat.Builder builderForValue) {
        if (catBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          catBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      public Builder mergeCat(com.jackxue.netty.example01.MessageData.Cat value) {
        if (catBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance()) {
            dataBody_ = com.jackxue.netty.example01.MessageData.Cat.newBuilder((com.jackxue.netty.example01.MessageData.Cat) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            catBuilder_.mergeFrom(value);
          }
          catBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      public Builder clearCat() {
        if (catBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          catBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      public com.jackxue.netty.example01.MessageData.Cat.Builder getCatBuilder() {
        return getCatFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.CatOrBuilder getCatOrBuilder() {
        if ((dataBodyCase_ == 3) && (catBuilder_ != null)) {
          return catBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.jackxue.netty.example01.MessageData.Cat) dataBody_;
          }
          return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.jackxue.netty.example01.Cat cat = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jackxue.netty.example01.MessageData.Cat, com.jackxue.netty.example01.MessageData.Cat.Builder, com.jackxue.netty.example01.MessageData.CatOrBuilder> 
          getCatFieldBuilder() {
        if (catBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
          }
          catBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jackxue.netty.example01.MessageData.Cat, com.jackxue.netty.example01.MessageData.Cat.Builder, com.jackxue.netty.example01.MessageData.CatOrBuilder>(
                  (com.jackxue.netty.example01.MessageData.Cat) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return catBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jackxue.netty.example01.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.jackxue.netty.example01.MyMessage)
    private static final com.jackxue.netty.example01.MessageData.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jackxue.netty.example01.MessageData.MyMessage();
    }

    public static com.jackxue.netty.example01.MessageData.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jackxue.netty.example01.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.jackxue.netty.example01.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jackxue.netty.example01.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jackxue.netty.example01.MessageData.Person.class, com.jackxue.netty.example01.MessageData.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jackxue.netty.example01.MessageData.Person)) {
        return super.equals(obj);
      }
      com.jackxue.netty.example01.MessageData.Person other = (com.jackxue.netty.example01.MessageData.Person) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jackxue.netty.example01.MessageData.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jackxue.netty.example01.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jackxue.netty.example01.Person)
        com.jackxue.netty.example01.MessageData.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jackxue.netty.example01.MessageData.Person.class, com.jackxue.netty.example01.MessageData.Person.Builder.class);
      }

      // Construct using com.jackxue.netty.example01.MessageData.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Person_descriptor;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Person getDefaultInstanceForType() {
        return com.jackxue.netty.example01.MessageData.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Person build() {
        com.jackxue.netty.example01.MessageData.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Person buildPartial() {
        com.jackxue.netty.example01.MessageData.Person result = new com.jackxue.netty.example01.MessageData.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jackxue.netty.example01.MessageData.Person) {
          return mergeFrom((com.jackxue.netty.example01.MessageData.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jackxue.netty.example01.MessageData.Person other) {
        if (other == com.jackxue.netty.example01.MessageData.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jackxue.netty.example01.MessageData.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jackxue.netty.example01.MessageData.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jackxue.netty.example01.Person)
    }

    // @@protoc_insertion_point(class_scope:com.jackxue.netty.example01.Person)
    private static final com.jackxue.netty.example01.MessageData.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jackxue.netty.example01.MessageData.Person();
    }

    public static com.jackxue.netty.example01.MessageData.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jackxue.netty.example01.Cat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.jackxue.netty.example01.Cat}
   */
  public static final class Cat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jackxue.netty.example01.Cat)
      CatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cat.newBuilder() to construct.
    private Cat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cat() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Cat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Cat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jackxue.netty.example01.MessageData.Cat.class, com.jackxue.netty.example01.MessageData.Cat.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jackxue.netty.example01.MessageData.Cat)) {
        return super.equals(obj);
      }
      com.jackxue.netty.example01.MessageData.Cat other = (com.jackxue.netty.example01.MessageData.Cat) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jackxue.netty.example01.MessageData.Cat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jackxue.netty.example01.MessageData.Cat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jackxue.netty.example01.Cat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jackxue.netty.example01.Cat)
        com.jackxue.netty.example01.MessageData.CatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Cat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Cat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jackxue.netty.example01.MessageData.Cat.class, com.jackxue.netty.example01.MessageData.Cat.Builder.class);
      }

      // Construct using com.jackxue.netty.example01.MessageData.Cat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jackxue.netty.example01.MessageData.internal_static_com_jackxue_netty_example01_Cat_descriptor;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Cat getDefaultInstanceForType() {
        return com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance();
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Cat build() {
        com.jackxue.netty.example01.MessageData.Cat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jackxue.netty.example01.MessageData.Cat buildPartial() {
        com.jackxue.netty.example01.MessageData.Cat result = new com.jackxue.netty.example01.MessageData.Cat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jackxue.netty.example01.MessageData.Cat) {
          return mergeFrom((com.jackxue.netty.example01.MessageData.Cat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jackxue.netty.example01.MessageData.Cat other) {
        if (other == com.jackxue.netty.example01.MessageData.Cat.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jackxue.netty.example01.MessageData.Cat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jackxue.netty.example01.MessageData.Cat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jackxue.netty.example01.Cat)
    }

    // @@protoc_insertion_point(class_scope:com.jackxue.netty.example01.Cat)
    private static final com.jackxue.netty.example01.MessageData.Cat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jackxue.netty.example01.MessageData.Cat();
    }

    public static com.jackxue.netty.example01.MessageData.Cat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Cat>
        PARSER = new com.google.protobuf.AbstractParser<Cat>() {
      @java.lang.Override
      public Cat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jackxue.netty.example01.MessageData.Cat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackxue_netty_example01_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackxue_netty_example01_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackxue_netty_example01_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackxue_netty_example01_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackxue_netty_example01_Cat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackxue_netty_example01_Cat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\022\033com.jackxue.netty.exa" +
      "mple01\"\270\001\n\tMyMessage\0227\n\010dataType\030\001 \002(\0162%" +
      ".com.jackxue.netty.example01.DataType\0225\n" +
      "\006person\030\002 \001(\0132#.com.jackxue.netty.exampl" +
      "e01.PersonH\000\022/\n\003cat\030\003 \001(\0132 .com.jackxue." +
      "netty.example01.CatH\000B\n\n\010dataBody\"#\n\006Per" +
      "son\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\" \n\003Cat\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005*4\n\010DataType\022\016\n\n" +
      "PersonType\020\001\022\013\n\007CatType\020\002\022\013\n\007DogType\020\003B," +
      "\n\033com.jackxue.netty.example01B\013MessageDa" +
      "taH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_jackxue_netty_example01_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jackxue_netty_example01_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackxue_netty_example01_MyMessage_descriptor,
        new java.lang.String[] { "DataType", "Person", "Cat", "DataBody", });
    internal_static_com_jackxue_netty_example01_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jackxue_netty_example01_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackxue_netty_example01_Person_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_com_jackxue_netty_example01_Cat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_jackxue_netty_example01_Cat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackxue_netty_example01_Cat_descriptor,
        new java.lang.String[] { "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
